//
//  AddTaskWorker.swift
//  CoreDataExample
//
//  Created by Kacper Wygoda on 02.05.2018.
//  Copyright (c) 2018 Kacper Wygoda. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
import CoreData

class AddTaskWorker {
    
    func mergeTaskModelIntoTaskToSave(taskToSave: Task, taskModel: AddTask.TaskModel) -> Task {
        taskToSave.colorIndex = taskModel.colorIndex
        taskToSave.date = taskModel.date
        taskToSave.subtitle = taskModel.subtitle
        taskToSave.taskDone = taskModel.taskDone
        taskToSave.time = taskModel.time
        taskToSave.title = taskModel.title
        
        return taskToSave
    }
    
    func fillUpTaskModel(task: Task) -> AddTask.TaskModel {
        var taskModel = AddTask.TaskModel()
        taskModel.colorIndex = task.colorIndex
        taskModel.date = task.date
        taskModel.subtitle = task.subtitle
        taskModel.taskDone = task.taskDone
        taskModel.time = task.time
        taskModel.title = task.title
        
        return taskModel
    }
    
    func createFilledIncorrectlyAlert() -> UIAlertController {
        let alertManager = UIAlertController()
        alertManager.title = "Check if all fields are filled properly"
        let action = UIAlertAction(title: "Ok", style: .default) { (action) in
            alertManager.dismiss(animated: true, completion: nil)
        }
        alertManager.addAction(action)
        
        return alertManager
    }
    
    func createUnfilledAlert() -> UIAlertController {
        let alertManager = UIAlertController()
        alertManager.title = "Some field are not filled at all"
        let action = UIAlertAction(title: "Ok", style: .default) { (action) in
            alertManager.dismiss(animated: true, completion: nil)
        }
        alertManager.addAction(action)
        
        return alertManager
    }
}
