//
//  MainRouter.swift
//  CoreDataExample
//
//  Created by Kacper Wygoda on 02.05.2018.
//  Copyright (c) 2018 Kacper Wygoda. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol MainRoutingLogic {
    func routeTo(vc: UIViewController)
}

protocol MainDataPassing {
    var dataStore: MainDataStore? { get }
}

class MainRouter: NSObject, MainRoutingLogic, MainDataPassing {
    weak var viewController: MainViewController?
    var dataStore: MainDataStore?
    
    func routeTo(vc: UIViewController) {
        switch vc {
        case is AddTaskViewController:
            let destinationNC = UIStoryboard.addNC()
            var destinationDS = (destinationNC.childViewControllers[0] as! AddTaskViewController).router!.dataStore!
            navigateToAddTaskVC(source: viewController!, destination: destinationNC)
            passDataToAddTaskVC(source: dataStore!, destination: &destinationDS)
        default:
            break
        }
    }
    
    private func navigateToAddTaskVC(source: MainViewController, destination: AddTaskNavigationController) {
        source.navigationController?.present(destination, animated: true, completion: nil)
    }
    
    private func passDataToAddTaskVC(source: MainDataStore, destination: inout AddTaskDataStore) {
        guard source.state == .editing else { return }
        destination.taskToSave = source.pickedTask
    }
    
}
