//
//  MainModels.swift
//  CoreDataExample
//
//  Created by Kacper Wygoda on 02.05.2018.
//  Copyright (c) 2018 Kacper Wygoda. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum Main {
    
    struct Tasks {
        var past: [Task]
        var today: [Task]
        var tomorrow: [Task]
        var upcoming7Days: [Task]
    }
    
    enum State {
        case editing
        case new
    }
    
    enum PrepareToRoute {
        struct Request {
            struct RouteToAddTaskVC {
                var state: State
            }
        }
        struct Response {
            struct RouteToAddTaskVC {
                var state: State
            }
        }
        struct ViewModel {
        }
    }
    
    enum UpdateDataStorage {
        struct Request {
            struct UpdatePickedTask {
                var pickedTask: Task
            }
        }
        struct Response {
        }
        struct ViewModel {
        }
    }
    
    enum FetchData {
        struct Request {
        }
        struct Response {
            struct FetchTasks {
                var tasks: Tasks
            }
        }
        struct ViewModel {
            struct FetchTasks {
                var tasks: Tasks
            }
        }
    }
}
